baseURL: "https://communitylawcourts.org"
languageCode: en-gb
title: Community Law Courts
theme: PaperMod           

params:
  ShowSharebuttons: true
    
  ShowPostNavLinks: true

menu:
    main:
        - identifier: agreement
          name: Agreement
          url: /agreement/
          weight: 10
        - identifier: about
          name: About
          url: /about/
          weight: 20
        - identifier: donations
          name: Donations
          url: /donations/
          weight: 30
        - identifier: services
          name: Services
          url: /services/
          weight: 40
        - identifier: gallery
          name: Gallery
          url: /gallery/
          weight: 50
        - identifier: contact
          name: Contact
          url: /contact/
          weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true            











